FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update
RUN apt-get install \
  software-properties-common \
  git \
  pip \
  clang-14 \
  lsb-release \
  cmake \
  nginx \
  curl \
  vim \
  -y
RUN ln -s /usr/bin/clang-14 /usr/local/bin/clang && \
  ln -s /usr/bin/clang++-14 /usr/local/bin/clang++
RUN pip install conan --quiet
ADD https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/3eb6693a91b1aa5b3863d087de1d189b72eeeec8/create-env-example.sh /scripts/create-env-example.sh
