version: "3.9"

services:
  emscripten-conan-repo-template:
    image: utkusarioglu/emscripten-conan-devcontainer:1.0.0
    volumes:
      - ..:/utkusarioglu/templates/emscripten-conan-repo-template
      - ../.conan:/root/.conan
